.mode csv
.import abilities.csv abilities
.import ability_changelog.csv ability_changelog
.import ability_changelog_prose.csv ability_changelog_prose
.import ability_flavor_text.csv ability_flavor_text
.import ability_names.csv ability_names
.import ability_prose.csv ability_prose
.import berries.csv berries
.import berry_firmness.csv berry_firmness
.import berry_firmness_names.csv berry_firmness_names
.import berry_flavors.csv berry_flavors
.import characteristics.csv characteristics
.import characteristic_text.csv characteristic_text
.import conquest_episode_names.csv conquest_episode_names
.import conquest_episodes.csv conquest_episodes
.import conquest_episode_warriors.csv conquest_episode_warriors
.import conquest_kingdom_names.csv conquest_kingdom_names
.import conquest_kingdoms.csv conquest_kingdoms
.import conquest_max_links.csv conquest_max_links
.import conquest_move_data.csv conquest_move_data
.import conquest_move_displacement_prose.csv conquest_move_displacement_prose
.import conquest_move_displacements.csv conquest_move_displacements
.import conquest_move_effect_prose.csv conquest_move_effect_prose
.import conquest_move_effects.csv conquest_move_effects
.import conquest_move_range_prose.csv conquest_move_range_prose
.import conquest_move_ranges.csv conquest_move_ranges
.import conquest_pokemon_abilities.csv conquest_pokemon_abilities
.import conquest_pokemon_evolution.csv conquest_pokemon_evolution
.import conquest_pokemon_moves.csv conquest_pokemon_moves
.import conquest_pokemon_stats.csv conquest_pokemon_stats
.import conquest_stat_names.csv conquest_stat_names
.import conquest_stats.csv conquest_stats
.import conquest_transformation_pokemon.csv conquest_transformation_pokemon
.import conquest_transformation_warriors.csv conquest_transformation_warriors
.import conquest_warrior_archetypes.csv conquest_warrior_archetypes
.import conquest_warrior_names.csv conquest_warrior_names
.import conquest_warrior_ranks.csv conquest_warrior_ranks
.import conquest_warrior_rank_stat_map.csv conquest_warrior_rank_stat_map
.import conquest_warriors.csv conquest_warriors
.import conquest_warrior_skill_names.csv conquest_warrior_skill_names
.import conquest_warrior_skills.csv conquest_warrior_skills
.import conquest_warrior_specialties.csv conquest_warrior_specialties
.import conquest_warrior_stat_names.csv conquest_warrior_stat_names
.import conquest_warrior_stats.csv conquest_warrior_stats
.import conquest_warrior_transformation.csv conquest_warrior_transformation
.import contest_combos.csv contest_combos
.import contest_effect_prose.csv contest_effect_prose
.import contest_effects.csv contest_effects
.import contest_type_names.csv contest_type_names
.import contest_types.csv contest_types
.import csv.txt.csv csv.txt
.import egg_group_prose.csv egg_group_prose
.import egg_groups.csv egg_groups
.import encounter_condition_prose.csv encounter_condition_prose
.import encounter_conditions.csv encounter_conditions
.import encounter_condition_value_map.csv encounter_condition_value_map
.import encounter_condition_value_prose.csv encounter_condition_value_prose
.import encounter_condition_values.csv encounter_condition_values
.import encounter_method_prose.csv encounter_method_prose
.import encounter_methods.csv encounter_methods
.import encounters.csv encounters
.import encounter_slots.csv encounter_slots
.import evolution_chains.csv evolution_chains
.import evolution_trigger_prose.csv evolution_trigger_prose
.import evolution_triggers.csv evolution_triggers
.import experience.csv experience
.import genders.csv genders
.import generation_names.csv generation_names
.import generations.csv generations
.import growth_rate_prose.csv growth_rate_prose
.import growth_rates.csv growth_rates
.import item_categories.csv item_categories
.import item_category_prose.csv item_category_prose
.import item_flag_map.csv item_flag_map
.import item_flag_prose.csv item_flag_prose
.import item_flags.csv item_flags
.import item_flavor_summaries.csv item_flavor_summaries
.import item_flavor_text.csv item_flavor_text
.import item_fling_effect_prose.csv item_fling_effect_prose
.import item_fling_effects.csv item_fling_effects
.import item_game_indices.csv item_game_indices
.import item_names.csv item_names
.import item_pocket_names.csv item_pocket_names
.import item_pockets.csv item_pockets
.import item_prose.csv item_prose
.import items.csv items
.import language_names.csv language_names
.import languages.csv languages
.import location_area_encounter_rates.csv location_area_encounter_rates
.import location_area_prose.csv location_area_prose
.import location_areas.csv location_areas
.import location_game_indices.csv location_game_indices
.import location_names.csv location_names
.import locations.csv locations
.import machines.csv machines
.import move_battle_style_prose.csv move_battle_style_prose
.import move_battle_styles.csv move_battle_styles
.import move_changelog.csv move_changelog
.import move_damage_classes.csv move_damage_classes
.import move_damage_class_prose.csv move_damage_class_prose
.import move_effect_changelog.csv move_effect_changelog
.import move_effect_changelog_prose.csv move_effect_changelog_prose
.import move_effect_prose.csv move_effect_prose
.import move_effects.csv move_effects
.import move_flag_map.csv move_flag_map
.import move_flag_prose.csv move_flag_prose
.import move_flags.csv move_flags
.import move_flavor_summaries.csv move_flavor_summaries
.import move_flavor_text.csv move_flavor_text
.import move_meta_ailment_names.csv move_meta_ailment_names
.import move_meta_ailments.csv move_meta_ailments
.import move_meta_categories.csv move_meta_categories
.import move_meta_category_prose.csv move_meta_category_prose
.import move_meta.csv move_meta
.import move_meta_stat_changes.csv move_meta_stat_changes
.import move_names.csv move_names
.import moves.csv moves
.import move_target_prose.csv move_target_prose
.import move_targets.csv move_targets
.import nature_battle_style_preferences.csv nature_battle_style_preferences
.import nature_names.csv nature_names
.import nature_pokeathlon_stats.csv nature_pokeathlon_stats
.import natures.csv natures
.import pal_park_area_names.csv pal_park_area_names
.import pal_park_areas.csv pal_park_areas
.import pal_park.csv pal_park
.import pokeathlon_stat_names.csv pokeathlon_stat_names
.import pokeathlon_stats.csv pokeathlon_stats
.import pokedexes.csv pokedexes
.import pokedex_prose.csv pokedex_prose
.import pokedex_version_groups.csv pokedex_version_groups
.import pokemon_abilities.csv pokemon_abilities
.import pokemon_color_names.csv pokemon_color_names
.import pokemon_colors.csv pokemon_colors
.import pokemon.csv pokemon
.import pokemon_dex_numbers.csv pokemon_dex_numbers
.import pokemon_egg_groups.csv pokemon_egg_groups
.import pokemon_evolution.csv pokemon_evolution
.import pokemon_form_generations.csv pokemon_form_generations
.import pokemon_form_names.csv pokemon_form_names
.import pokemon_form_pokeathlon_stats.csv pokemon_form_pokeathlon_stats
.import pokemon_forms.csv pokemon_forms
.import pokemon_game_indices.csv pokemon_game_indices
.import pokemon_habitat_names.csv pokemon_habitat_names
.import pokemon_habitats.csv pokemon_habitats
.import pokemon_items.csv pokemon_items
.import pokemon_move_method_prose.csv pokemon_move_method_prose
.import pokemon_move_methods.csv pokemon_move_methods
.import pokemon_moves.csv pokemon_moves
.import pokemon_shape_prose.csv pokemon_shape_prose
.import pokemon_shapes.csv pokemon_shapes
.import pokemon_species.csv pokemon_species
.import pokemon_species_flavor_summaries.csv pokemon_species_flavor_summaries
.import pokemon_species_flavor_text.csv pokemon_species_flavor_text
.import pokemon_species_names.csv pokemon_species_names
.import pokemon_species_prose.csv pokemon_species_prose
.import pokemon_stats.csv pokemon_stats
.import pokemon_types.csv pokemon_types
.import region_names.csv region_names
.import regions.csv regions
.import stat_names.csv stat_names
.import stats.csv stats
.import super_contest_combos.csv super_contest_combos
.import super_contest_effect_prose.csv super_contest_effect_prose
.import super_contest_effects.csv super_contest_effects
.import translations.csv translations
.import type_efficacy.csv type_efficacy
.import type_game_indices.csv type_game_indices
.import type_names.csv type_names
.import types.csv types
.import version_group_pokemon_move_methods.csv version_group_pokemon_move_methods
.import version_group_regions.csv version_group_regions
.import version_groups.csv version_groups
.import version_names.csv version_names
.import versions.csv versions
